### ISSUE TITLE
Address boundary error

### ISSUE THREAD

**Issue by anddam** [fjolnir/TLC#3]
State: updated TLC, luajit 2.0.1 from macports on 10.7 system, window.lua is at the same fs level of objc/ folder.

I get an _Address boundary error_ after the call to

```
bs.loadFramework("AppKit", true)
```

while the call to Foundation returns just fine.

I'm able to run the Cocoa application with TLC using plain objc.loadFramework() rather than BridgeScript but having to define each constant after looking their value in header is quite uncomfortable.

Here's the actual output with backtrace:

```
me@biboop ~/D/D/L/TLC> luajit window.lua
fish: Job 1, 'luajit window.lua ' terminated by signal SIGSEGV (Address boundary error)
me@biboop ~/D/D/L/TLC> gdb luajit
GNU gdb 6.3.50-20050815 (Apple version gdb-1824) (Wed Feb  6 22:51:23 UTC 2013)
Copyright 2004 Free Software Foundation, Inc.
GDB is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain conditions.
Type "show copying" to see the conditions.
There is absolutely no warranty for GDB.  Type "show warranty" for details.
This GDB was configured as "x86_64-apple-darwin"...Reading symbols for shared libraries .. done

(gdb) r window.lua
Starting program: /opt/local/bin/luajit window.lua
Reading symbols for shared libraries +........................ done
Reading symbols for shared libraries ..... done
Reading symbols for shared libraries .... done
Reading symbols for shared libraries ................................ done
Reading symbols for shared libraries ................................................................... done
Reading symbols for shared libraries .. done
Reading symbols for shared libraries . done
Reading symbols for shared libraries . done
Reading symbols for shared libraries ........ done
Reading symbols for shared libraries . done

Program received signal EXC_BAD_ACCESS, Could not access memory.
Reason: 13 at address: 0x0000000000000000
0x00007fff85ffbfe6 in libunwind::CompactUnwinder_x86_64<libunwind::LocalAddressSpace>::stepWithCompactEncodingFrameless ()
(gdb) bt
#0  0x00007fff85ffbfe6 in libunwind::CompactUnwinder_x86_64<libunwind::LocalAddressSpace>::stepWithCompactEncodingFrameless ()
#1  0x00007fff85ffa20c in libunwind::CompactUnwinder_x86_64<libunwind::LocalAddressSpace>::stepWithCompactEncoding ()
#2  0x00007fff85ffa171 in libunwind::UnwindCursor<libunwind::LocalAddressSpace, libunwind::Registers_x86_64>::step ()
#3  0x00007fff85ff9931 in _Unwind_RaiseException ()
#4  0x0000000100006fca in main ()
(gdb)
```

**Comment by fjolnir** [comment]
I'm afraid I can't reproduce this on 10.8 (and I don't have a 10.7 machine handy)
This backtrace looks like it's crashing inside the crash reporter.. which is queer to say the least

can you try to find which line it's crashing on?

**Comment by anddam** [comment]
The failing line is the pcall to ffi.cdef in _init.lua_:

```
-- We need to wrap the def in a pcall so that we don't crash in case the struct is too big (As is the case with one in IOKit)
local success, err = pcall(ffi.cdef, typeStr)
```

The comment had an hint about this, I'm not sure why the pcall is failing though, in my case it hangs while loading HIToolbox framework from AppKit.

**Comment by anddam** [comment]
The SIGSEGV is due to the use of a struct that hasn't previously been defined, in this case it's struct FSSpec in struct HFSFlavor. I read FSSpec is deprecated in OSX.

I dumped all the cdef that have been made before the crash:

```
struct CGPoint {  double x; double y; }
struct TabletPointRec {  int absX; int absY; int absZ; unsigned short buttons; unsigned short pressure; short tiltX; short tiltY; unsigned short rotation; short tangentialPressure; unsigned short deviceID; short vendor1; short vendor2; short vendor3; }
struct InkPoint {  struct CGPoint point; struct TabletPointRec tabletPointData; unsigned int keyModifiers; }
struct CGSize {  double field1; double field2; }
struct CGRect {  struct CGPoint field1; struct CGSize field2; }
struct AlertStdAlertParamRec {  BOOL movable; BOOL helpButton; void *filterProc; char * defaultText; char * cancelText; char * otherText; short defaultButton; short cancelButton; unsigned short position; }
struct AlertStdCFStringAlertParamRec {  unsigned int version; BOOL movable; BOOL helpButton; struct __CFString *defaultText; struct __CFString *cancelText; struct __CFString *otherText; short defaultButton; short cancelButton; unsigned short position; unsigned int flags; struct OpaqueIconRef *icon; }
struct Rect {  short top; short left; short bottom; short right; }
struct AlertTemplate {  struct Rect boundsRect; short itemsID; short stages; }
struct BasicWindowDescription {  unsigned int descriptionSize; struct Rect windowContentRect; struct Rect windowZoomRect; void *windowRefCon; unsigned int windowStateFlags; unsigned int windowPositionMethod; unsigned int windowDefinitionVersion; union  {  struct  {  short windowDefProc; BOOL windowHasCloseBox; } versionOne; struct  {  unsigned int windowClass; unsigned int windowAttributes; } versionTwo; } windowDefinition; }
struct Point {  short v; short h; }
struct ContextualMenuInterfaceStruct {  void *_reserved; void *QueryInterface; void *AddRef; void *Release; void *ExamineContext; void *HandleSelection; void *PostMenuCleanup; }
struct ControlImageContentInfo {  short contentType; union  {  short resID; struct OpaqueIconRef *iconRef; struct CGImage *imageRef; } u; }
struct ControlEditTextSelectionRec {  short selStart; short selEnd; }
struct RGBColor {  unsigned short red; unsigned short green; unsigned short blue; }
struct ControlFontStyleRec {  short flags; short font; short size; short style; short mode; short just; struct RGBColor foreColor; struct RGBColor backColor; }
struct ControlID {  unsigned int signature; int id; }
struct ControlKind {  unsigned int signature; unsigned int kind; }
struct ControlTabEntry {  struct ControlImageContentInfo *icon; struct __CFString *name; BOOL enabled; }
struct ControlTabInfoRec {  short version; short iconSuiteID; unsigned char  name[256]; }
struct ControlTabInfoRecV1 {  short version; short iconSuiteID; struct __CFString *name; }
struct ControlTemplate {  struct Rect controlRect; short controlValue; BOOL controlVisible; unsigned char fill; short controlMaximum; short controlMinimum; short controlDefProcID; int controlReference; unsigned char  controlTitle[256]; }
struct ColorSpec {  short value; struct RGBColor rgb; }
struct CtlCTab {  int ccSeed; short ccRider; short ctSize; struct ColorSpec  ctTable[4]; }
struct DataBrowserAccessibilityItemInfoV0 {  unsigned long long container; unsigned long long item; unsigned long long columnProperty; unsigned int propertyPart; }
struct DataBrowserAccessibilityItemInfoV1 {  unsigned long long container; unsigned long long item; unsigned long long columnProperty; unsigned int propertyPart; unsigned long long rowIndex; unsigned long long columnIndex; }
struct DataBrowserAccessibilityItemInfo {  unsigned int version; union  {  struct DataBrowserAccessibilityItemInfoV0 v0; struct DataBrowserAccessibilityItemInfoV1 v1; } u; }
struct DataBrowserCallbacks {  unsigned int version; union{}  u; }
struct DataBrowserCustomCallbacks {  unsigned int version; union{}  u; }
struct DataBrowserPropertyDesc {  unsigned long long propertyID; unsigned int propertyType; unsigned int propertyFlags; }
struct DataBrowserListViewHeaderDesc {  unsigned int version; unsigned short minimumWidth; unsigned short maximumWidth; short titleOffset; struct __CFString *titleString; unsigned short initialOrder; struct ControlFontStyleRec btnFontStyle; struct ControlImageContentInfo btnContentInfo; }
struct DataBrowserListViewColumnDesc {  struct DataBrowserPropertyDesc propertyDesc; struct DataBrowserListViewHeaderDesc headerBtnDesc; }
struct DialogTemplate {  struct Rect boundsRect; short procID; BOOL visible; BOOL filler1; BOOL goAwayFlag; BOOL filler2; int refCon; short itemsID; unsigned char  title[256]; }
struct EvQEl {  struct QElem *qLink; short qType; unsigned short evtQWhat; unsigned long long evtQMessage; unsigned int evtQWhen; struct Point evtQWhere; unsigned short evtQModifiers; }
struct EventHotKeyID {  unsigned int signature; unsigned int id; }
struct EventRecord {  unsigned short what; unsigned long long message; unsigned int when; struct Point where; unsigned short modifiers; }
struct EventTypeSpec {  unsigned int eventClass; unsigned int eventKind; }
struct FileTranslationList {  unsigned long long modDate; unsigned long long groupCount; }
struct FileTypeSpec {  unsigned int format; long long hint; unsigned int flags; unsigned int catInfoType; unsigned int catInfoCreator; }
struct FileTranslationSpec {  unsigned int componentSignature; void *translationSystemInfo; struct FileTypeSpec src; struct FileTypeSpec dst; }
struct GetGrowImageRegionRec {  struct Rect growRect; struct OpaqueRgnHandle *growImageRegion; }
struct GetWindowRegionRec {  struct OpaqueRgnHandle *winRgn; unsigned short regionCode; }
struct HFSFlavor {  unsigned int fileType; unsigned int fileCreator; unsigned short fdFlags; struct FSSpec fileSpec; }
```

**Comment by fjolnir** [comment]
That looks like a luajit bug then. (Assuming it's crashing on the actual _definition_) It should just error out and that error be caught by the pcall.

But in any case, the bridgesupport stuff should be rewritten to use libclang instead of the xml monsters.

**Comment by anddam** [comment]
Closing since it's not a TLC issue.

**Comment by anddam** [comment]
As future reference it seems to be related to clang and MACOSX_DEPLOYMENT_TARGET value.

  https://trac.macports.org/changeset/105762
